### ISSUE TITLE
annotations bug

### ISSUE THREAD

**Issue by GrafLearnt** [bauerji/flask-pydantic#89]
When 
`from __future__ import annotations`
is imported got following error:

```python
        **{
            key: value
            for key, value in query_params.to_dict(flat=False).items()
>           if key in model.__fields__ and model.__fields__[key].is_complex()
        },
    }
E   AttributeError: 'str' object has no attribute '__fields__'
```

local `model` variable became `str` instead of pydantic class

> 
> Virtualenv
> Python:         3.11.7
> Implementation: CPython
> 
> System
> Platform:   darwin
> OS:         posix
> Python:     3.11.7
>

**Comment by yctomwang** [comment]
@GrafLearnt Hi there, thank you for your bug report. Can you please include some more details? Like the model you are trying to verify against? it be nice if you could include a minimal example for us to look into!

**Comment by yctomwang** [comment]
This is my understanding of the problem, is that if you have from __future__ import annotations anywhere in the code, the package will have problem like 
<img width="1071" alt="image" src="https://github.com/bauerji/flask-pydantic/assets/69774548/1b24a2ac-d0fb-4e12-97f6-120595a7b7cc">

**Comment by ksikka** [comment]
I have an issue related to this and type-hint-based validation.

When you remove `from __future__ import annotations` the error no longer occurs:

```
[2025-11-01 23:15:17,862] ERROR in app: Exception on /test [POST]
Traceback (most recent call last):
  File "/home/ksikka/PycharmProjects/flask_pydantic_string_bug/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksikka/PycharmProjects/flask_pydantic_string_bug/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksikka/PycharmProjects/flask_pydantic_string_bug/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksikka/PycharmProjects/flask_pydantic_string_bug/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksikka/PycharmProjects/flask_pydantic_string_bug/.venv/lib/python3.12/site-packages/flask_pydantic/core.py", line 205, in wrapper
    issubclass(body_model, V1BaseModel)
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class
```

and the example code is 
```
from __future__ import annotations

from pydantic import BaseModel
from flask import Flask
from flask_pydantic import validate

app = Flask(__name__)


class MockRequestModel(BaseModel):
    a: int = 3


@app.post("/test")
@validate()
def test(body: MockRequestModel): 
    return {}


if __name__ == "__main__":
    app.run()

```

> Python 3.12.3
> Flask-Pydantic 0.13.2
> pydantic 2.12.3

**Comment by ksikka** [comment]
Line 200 of core.py 
>             body_in_kwargs = func.__annotations__.get("body")

`body_in_kwargs` is a string due to the `from __future__ import annotations`.

Seems a solution is to replace `.__annotations__` with `typing.get_type_hints`. Credit due to AI for the idea. It makes sense to me.

I am interested in contributing but I don't know if this is a good starter bug 😆  Maybe if someone from the core contributors encourages me to try, I will. else I'll leave it to the pros.  In the mean time I can't use flask-pydantic :(

This should be considered a pretty severe bug, I would think.

**Comment by stv8** [comment]
@ksikka yes give it a try and make sure tests pass, if all works out then we can get it merged in soon
